### ISSUE TITLE
.CSS recognized as .SCSS

### ISSUE THREAD

**Issue by oncecoupled** [csscomb/sublime-csscomb#61]
When I try to run this, nothing happens. My file is saved as .css and my syntax is set to css as well. The following console message is given:
=========================
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/LG/Library/Application Support/Sublime Text 3/Packages/CSScomb/CSScomb.py", line 18, in run
    syntax = self.get_syntax()
  File "/Users/LG/Library/Application Support/Sublime Text 3/Packages/CSScomb/CSScomb.py", line 79, in get_syntax
    if self.is_scss():
  File "/Users/LG/Library/Application Support/Sublime Text 3/Packages/CSScomb/CSScomb.py", line 112, in is_scss
    return self.view.scope_name(0).startswith('source.scss') or self.view.file_name().endswith('.scss')
AttributeError: 'NoneType' object has no attribute 'endswith'
=========================
The weird thing is that it *sometimes* will work. I just haven't figured out when that is, yet.

**Comment by Oleg2tor** [comment]
Has same problem - seems like something wrong with destination / environment path for python.

**Comment by freedyc** [comment]
asfsaf

**Comment by rishirdua** [comment]
+1. Same error
