### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by HbIXA** [csscomb/sublime-csscomb#67]
Traceback (most recent call last):
  File "C:\Users\kuznetsov_ea\Downloads\Sublime Text Build 3083 x64\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "C:\Users\kuznetsov_ea\Downloads\Sublime Text Build 3083 x64\Data\Packages\CSScomb\CSScomb.py", line 35, in run
    combed = self.comb(originalBuffer, syntax, config)
  File "C:\Users\kuznetsov_ea\Downloads\Sublime Text Build 3083 x64\Data\Packages\CSScomb\CSScomb.py", line 53, in comb
    sublime.error_message('CSScomb error:\n%s' % stderr.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 7: invalid start byte

**Comment by Alecto** [comment]
doenst work too

**Comment by dmegatool** [comment]
Check that NodeJS is working. I had a very similar error (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 82: invalid start byte). I had NodeJS installed but it seems the installation failed. When testing with "node -v" in the command line, I wouldn't get the version. 

So in the end I end up completly reinstalling NodeJS from scratch, made sure it worked correctly by checking in the Windows command line. Then cssComb worked. Wish I had the error about NodeJS.
