### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 7: invalid start byte

### ISSUE THREAD

**Issue by helloyan** [csscomb/sublime-csscomb#74]
Traceback (most recent call last):
  File "D:\PortableProgram\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "D:\PortableProgram\Sublime Text 3\Data\Packages\sublime-csscomb\CSScomb.py", line 27, in run
    combed = self.comb(originalBuffer, syntax, config)
  File "D:\PortableProgram\Sublime Text 3\Data\Packages\sublime-csscomb\CSScomb.py", line 53, in comb
    sublime.error_message('CSScomb error:\n%s' % stderr.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 7: invalid start byte

**Comment by Alecto** [comment]
doenst work too

**Comment by napastyuk** [comment]
Me too. Error occurs if using -moz* prefixes in the sort-order settings.

**Comment by FRITS-Kh** [comment]
Me too.

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "C:\Users\myusername\AppData\Roaming\Sublime Text 3\Packages\CSScomb\CSScomb.py", line 27, in run
    combed = self.comb(originalBuffer, syntax, config)
  File "C:\Users\myusername\AppData\Roaming\Sublime Text 3\Packages\CSScomb\CSScomb.py", line 53, in comb
    sublime.error_message('CSScomb error:\n%s' % stderr.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 0: invalid start byte
